:schedule:
  fill_db:
    cron:  '*/5 * * * * '   # Runs once per minute
    class: RecommenderWorker
  matrix_computation:
    cron:  '*/30 * * * * '   # Runs once per minute
    class: MatrixWorker
